---
- set_fact: rdbms=mariadb

- set_fact: rdbms=mysql
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version <= 6

- set_fact: rdbms_root_pw="{{ lookup('password', '~/' + rdbms + '_root_password length=15') }}"

- set_fact: rdbms_service=mariadb
  when: rdbms == 'mariadb'

- set_fact: rdbms_service=mysqld
  when: rdbms == 'mysql'

- set_fact: log_file=/var/log/mysql.log
  when: rdbms == 'mysql'

- set_fact: log_file=/var/log/mariadb/mariadb.log
  when: rdbms == 'mariadb'

- yum: name={{ item }} state=installed
  with_items:
  - "{{ rdbms }}-server"
  - MySQL-python

- template: src=custom.cnf dest=/etc/my.cnf.d/custom.cnf
  notify: restart mariadb
  when: rdbms == 'mariadb'

- template: src=my.server.cnf dest=/etc/my.cnf
  notify: restart mysqld
  when: rdbms == 'mysqld'

- template: src=my.client.cnf dest=/root/.my.cnf mode=600 owner=root group=root

- service: name={{ rdbms }} enabled=yes state=started

- copy: mode=0755 src=dump_db.sh dest=/usr/local/bin/dump_{{ rdbms }}.sh

- cron: minute=15 hour=4 name="backup {{ rdbms }}" job=/usr/local/bin/dump_{{ rdbms }}.sh
